--- # Build file for running on local machine on an ec2 instance
- hosts: local
  user: ec2-user
  become: yes
  become_method: sudo
  connection: local
  gather_facts: yes
  roles:
    - rabbitmq
    - http_api

