- name: install nodesrc
  get_url: 
    url: https://rpm.nodesource.com/setup_11.x
    dest: /tmp/node.sh
- name: exec it
  shell: bash /tmp/node.sh
- name: install nodejs
  package:
    name: nodejs
    state: latest
- name: create app dir
  file: 
    state: directory
    name: /app
- name: copy app files
  copy:
    dest: /app
    src: "{{ item }}"
  with_items:
    - package.json
    - src/index.js
- name: install files
  shell: npm i 
  args:
    chdir: /app
